# -*- coding: utf-8 -*-
"""olist_financial_analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oRF9i8wkfZZ3ADLV-zSoOEvPh4away_d

# Financial Analytics Case Study  
## Olist E-commerce: Revenue, Accounting & Profitability Analysis

**Author:** Antonella Ríos  

### Project Objective
This project analyzes the financial performance of a Brazilian e-commerce platform
using transactional data.

The analysis combines **data analytics and accounting principles**
to simulate financial reporting and generate business insights.

## Data Access Note

The dataset was uploaded manually as a ZIP file due to temporary compatibility
issues between Google Colab (Python 3.12) and the Kaggle API client.

In a production environment, data ingestion would be handled
via automated pipelines or APIs.
"""

!unzip -o brazilian-ecommerce.zip

!ls

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

orders = pd.read_csv('olist_orders_dataset.csv')
payments = pd.read_csv('olist_order_payments_dataset.csv')
items = pd.read_csv('olist_order_items_dataset.csv')
products = pd.read_csv('olist_products_dataset.csv')
translation = pd.read_csv('product_category_name_translation.csv')

"""## Data Quality Audit

Before performing any financial analysis, a data quality audit is conducted
to ensure reliability and accuracy in financial reporting.
"""

def data_quality_report(df, name):
    print(f"--- Data Quality Report: {name} ---")
    print(f"Total records: {len(df)}")
    print("Missing values:")
    print(df.isnull().sum())
    print(f"Duplicated rows: {df.duplicated().sum()}")

    if 'payment_value' in df.columns:
        negatives = (df['payment_value'] < 0).sum()
        print(f"Negative payment values: {negatives}")
    print("-" * 40)

data_quality_report(orders, "Orders")
data_quality_report(payments, "Payments")

"""## Revenue Recognition Logic

Revenue is recognized **only when the order is delivered**.

This conservative approach avoids recognizing revenue from
canceled or undelivered orders.
"""

df = pd.merge(orders, payments, on='order_id')
df['order_purchase_timestamp'] = pd.to_datetime(df['order_purchase_timestamp'])

df_delivered = df[df['order_status'] == 'delivered'].copy()

"""## Time Scope Disclaimer

The dataset ends in 2018 and the final months contain incomplete records.

To avoid misleading trends, time-based analyses are limited
to **complete accounting periods only**.

"""

df_delivered['period'] = df_delivered['order_purchase_timestamp'].dt.to_period('M')

monthly_revenue = (
    df_delivered
    .groupby('period')['payment_value']
    .sum()
    .reset_index()
)

monthly_revenue['period'] = monthly_revenue['period'].astype(str)

# Filter incomplete periods (keep data until August 2018)
monthly_revenue = monthly_revenue[monthly_revenue['period'] <= '2018-08']

plt.figure(figsize=(12,6))
sns.lineplot(data=monthly_revenue, x='period', y='payment_value', marker='o')

plt.title('Monthly Revenue Evolution (Delivered Orders Only)')
plt.xlabel('Accounting Period')
plt.ylabel('Total Revenue')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""## Double-Entry Accounting Simulation

Each delivered sale generates:
- A **Debit** in an Asset account (cash or bank)
- A **Credit** in Sales Revenue

This section simulates a simplified General Ledger.
"""

chart_of_accounts = {
    'credit_card': '1.01 Bank - Credit Cards',
    'debit_card': '1.01 Bank - Debit Cards',
    'boleto': '1.02 Cash / Boleto',
    'voucher': '1.03 Vouchers'
}

journal = []

# Note: iterrows is used here for clarity.
# In production, vectorized operations would be preferred.
for _, row in df_delivered.iterrows():
    account = chart_of_accounts.get(row['payment_type'], '1.04 Other Assets')
    amount = row['payment_value']

    journal.append({'Account': account, 'Debit': amount, 'Credit': 0})
    journal.append({'Account': '4.01 Sales Revenue', 'Debit': 0, 'Credit': amount})

ledger = pd.DataFrame(journal)

trial_balance = ledger.groupby('Account').sum().reset_index()

trial_balance_style = trial_balance.copy()

for col in ['Debit', 'Credit']:
    trial_balance_style[col] = trial_balance_style[col].apply(lambda x: f"${x:,.2f}")

trial_balance_style

"""## Profitability Analysis

Product cost (COGS) is not available in the dataset.

This analysis focuses on:
- Product revenue
- Logistics costs (freight)

The resulting metric represents a **Logistics Contribution Margin**,
not a true Gross Profit.

"""

df_profit = pd.merge(
    df_delivered[['order_id']],
    items[['order_id', 'price', 'freight_value']],
    on='order_id'
)

total_sales = df_profit['price'].sum()
total_freight = df_profit['freight_value'].sum()
logistics_margin = total_sales - total_freight

total_sales, total_freight, logistics_margin

"""## Revenue Erosion Analysis – Waterfall Chart

This chart illustrates how total sales are reduced by logistics costs
to reach the final contribution margin.

This represents a **logistics contribution margin**, not gross profit.
"""

import numpy as np

names = ['Total Sales', 'Logistics Costs', 'Contribution Margin']
values = [total_sales, -total_freight, logistics_margin]

cumulative = np.cumsum(values)
base = np.zeros(len(values))
base[1:] = cumulative[:-1]
base[-1] = 0

plt.figure(figsize=(10,6))
colors = ['#2ecc71', '#e74c3c', '#3498db']

for i in range(len(values)):
    plt.bar(names[i], values[i], bottom=base[i], color=colors[i])
    plt.text(i, base[i] + values[i]/2, f'${values[i]/1e6:.1f}M',
             ha='center', va='center', color='white', fontweight='bold')

plt.title('Revenue Erosion Analysis (Logistics Impact)')
plt.ylabel('Amount in Millions ($)')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""## Key Business Insights

- Credit card payments represent the primary revenue channel.
- Logistics costs have a significant impact on the contribution margin.
- Revenue shows consistent growth until mid-2018, after which data becomes incomplete.

This analysis highlights the importance of logistics cost control
to preserve profitability in e-commerce operations.
"""